import jsPDF from "jspdf";
import "jspdf-autotable";

// Extend jsPDF type for autoTable
declare module "jspdf" {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface InvoiceData {
  invoice_number: string;
  invoice_date: string;
  due_date?: string | null;
  customer_name: string;
  company_name: string;
  company_logo?: string | null;
  items: {
    name: string;
    quantity: number;
    unit_price: number;
    total: number;
  }[];
  subtotal: number;
  discount_rate: number;
  discount_amount: number;
  tax_rate: number;
  tax_amount: number;
  total: number;
  paid_amount: number;
  notes?: string | null;
}

// Helper function to load image as base64
const loadImageAsBase64 = (url: string): Promise<string | null> => {
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      if (ctx) {
        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL("image/png"));
      } else {
        resolve(null);
      }
    };
    img.onerror = () => resolve(null);
    img.src = url;
  });
};

export const exportInvoiceToPDF = async (invoice: InvoiceData) => {
  const doc = new jsPDF();
  
  let headerStartY = 20;
  
  // Add logo if available
  if (invoice.company_logo) {
    try {
      const logoBase64 = await loadImageAsBase64(invoice.company_logo);
      if (logoBase64) {
        // Add logo centered at top
        doc.addImage(logoBase64, "PNG", 85, 10, 40, 20);
        headerStartY = 35;
      }
    } catch (error) {
      console.error("Error loading logo:", error);
    }
  }
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(33, 37, 41);
  doc.text(invoice.company_name, 105, headerStartY, { align: "center" });
  
  doc.setFontSize(16);
  doc.setTextColor(100, 100, 100);
  doc.text("Invoice / Faktura", 105, headerStartY + 10, { align: "center" });
  
  // Invoice info
  doc.setFontSize(10);
  doc.setTextColor(33, 37, 41);
  
  const infoStartY = headerStartY + 25;
  doc.text(`Invoice Number: ${invoice.invoice_number}`, 20, infoStartY);
  doc.text(`Date: ${invoice.invoice_date}`, 20, infoStartY + 7);
  if (invoice.due_date) {
    doc.text(`Due Date: ${invoice.due_date}`, 20, infoStartY + 14);
  }
  
  doc.text(`Customer: ${invoice.customer_name}`, 120, infoStartY);
  
  // Items table
  const tableData = invoice.items.map((item) => [
    item.name,
    item.quantity.toString(),
    `${item.unit_price.toFixed(2)} EGP`,
    `${item.total.toFixed(2)} EGP`,
  ]);
  
  doc.autoTable({
    startY: infoStartY + (invoice.due_date ? 25 : 18),
    head: [["Item", "Quantity", "Unit Price", "Total"]],
    body: tableData,
    theme: "striped",
    headStyles: { fillColor: [59, 130, 246] },
    styles: { fontSize: 9 },
  });
  
  // Totals
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  
  doc.setFontSize(10);
  doc.text(`Subtotal: ${invoice.subtotal.toFixed(2)} EGP`, 140, finalY);
  doc.text(`Discount (${invoice.discount_rate}%): -${invoice.discount_amount.toFixed(2)} EGP`, 140, finalY + 7);
  doc.text(`Tax (${invoice.tax_rate}%): ${invoice.tax_amount.toFixed(2)} EGP`, 140, finalY + 14);
  
  doc.setFontSize(12);
  doc.setFont(undefined as any, "bold");
  doc.text(`Total: ${invoice.total.toFixed(2)} EGP`, 140, finalY + 24);
  
  doc.setFontSize(10);
  doc.setFont(undefined as any, "normal");
  doc.setTextColor(34, 197, 94);
  doc.text(`Paid: ${invoice.paid_amount.toFixed(2)} EGP`, 140, finalY + 32);
  
  doc.setTextColor(220, 38, 38);
  doc.text(`Remaining: ${(invoice.total - invoice.paid_amount).toFixed(2)} EGP`, 140, finalY + 40);
  
  // Notes
  if (invoice.notes) {
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.text(`Notes: ${invoice.notes}`, 20, finalY + 50);
  }
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by EDOXO System", 105, 285, { align: "center" });
  
  // Save
  doc.save(`Invoice-${invoice.invoice_number}.pdf`);
};

interface ReportData {
  title: string;
  period: string;
  company_name: string;
  stats: { label: string; value: string }[];
  tableData?: {
    headers: string[];
    rows: string[][];
  };
}

export const exportReportToPDF = (report: ReportData) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(18);
  doc.setTextColor(33, 37, 41);
  doc.text(report.company_name, 105, 15, { align: "center" });
  
  doc.setFontSize(14);
  doc.text(report.title, 105, 25, { align: "center" });
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Period: ${report.period}`, 105, 33, { align: "center" });
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 105, 40, { align: "center" });
  
  // Stats
  let currentY = 55;
  doc.setFontSize(11);
  doc.setTextColor(33, 37, 41);
  
  report.stats.forEach((stat, index) => {
    const x = 20 + (index % 2) * 90;
    const y = currentY + Math.floor(index / 2) * 15;
    doc.text(`${stat.label}: ${stat.value}`, x, y);
  });
  
  // Table if provided
  if (report.tableData && report.tableData.rows.length > 0) {
    const tableStartY = currentY + Math.ceil(report.stats.length / 2) * 15 + 10;
    
    doc.autoTable({
      startY: tableStartY,
      head: [report.tableData.headers],
      body: report.tableData.rows,
      theme: "striped",
      headStyles: { fillColor: [59, 130, 246] },
      styles: { fontSize: 8 },
    });
  }
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by EDOXO System", 105, 285, { align: "center" });
  
  // Save
  const fileName = `${report.title.replace(/\s+/g, "-")}-${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
};

export const exportReceivablesReport = (data: {
  company_name: string;
  total_receivables: number;
  total_overdue: number;
  customers: { name: string; debt: number; overdue: number }[];
}) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(18);
  doc.text(data.company_name, 105, 15, { align: "center" });
  
  doc.setFontSize(14);
  doc.text("Receivables Report / Taqrir Al-Mustahaqat", 105, 25, { align: "center" });
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 105, 33, { align: "center" });
  
  // Summary
  doc.setFontSize(11);
  doc.setTextColor(33, 37, 41);
  doc.text(`Total Receivables: ${data.total_receivables.toLocaleString()} EGP`, 20, 50);
  doc.setTextColor(220, 38, 38);
  doc.text(`Overdue Amount: ${data.total_overdue.toLocaleString()} EGP`, 20, 58);
  
  // Customer table
  if (data.customers.length > 0) {
    const tableData = data.customers.map((c) => [
      c.name,
      `${c.debt.toLocaleString()} EGP`,
      `${c.overdue.toLocaleString()} EGP`,
    ]);
    
    doc.autoTable({
      startY: 70,
      head: [["Customer", "Total Debt", "Overdue"]],
      body: tableData,
      theme: "striped",
      headStyles: { fillColor: [220, 38, 38] },
      styles: { fontSize: 9 },
    });
  }
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by EDOXO System", 105, 285, { align: "center" });
  
  doc.save(`Receivables-Report-${new Date().toISOString().split("T")[0]}.pdf`);
};
